#spring.profiles.active=@spring.profiles.active@

spring.profiles.active=dev

server.port=8081

spring.application.name=payment-validation-service


# Connect to config server
spring.config.import=optional:configserver:http://localhost:8888

#spring.cloud.config.label=main

management.endpoints.web.exposure.include=health,refresh

stripe-provider.create-session-url=http://localhost:8083/v1/payments