server.port=8888

spring.application.name=payment-config-server

#spring.profiles.active=native


#my properties configuration is classpath/config/ location
#spring.cloud.config.server.native.search-locations=classpath:/config/

#read the config files from local file system C:\Users\sheet\OneDrive\Documents\Stripe\config
#spring.cloud.config.server.native.searchLocations=file:///C:/Users/sheet/OneDrive/Documents/Stripe/config

#Enabling git as the backend for configuration properties
#spring.cloud.config.server.git.uri=https://shitalpatle0024@bitbucket.org/myworkspaceforlearning/payment-config-properties.git
spring.cloud.config.server.git.uri=https://shitalpatle0024@bitbucket.org/myworkspaceforlearning/payment-config-properties.git

#Branch (Important)
spring.cloud.config.server.git.default-label=main

spring.cloud.config.server.git.username=shitalpatle0024

spring.cloud.config.server.git.password=ATATT3xFfGF0xNm-S8XqrUvPd6Sg28bMTgTsj2edBPNYDc-xYjFD6APcuk7JNiLKcwWjkJoYJYOpj_n-J6y_JQd5XMcqm8ly2FIcbUZqLuv3W6AzQ_Qu7vXzZl54ViQMXCpW69fcA8S20SWBqzk02K3hNnmoUdfV9OAnyLSzCBBbXedYrrwcRfg=2A975BD5

#spring.cloud.config.server.git.clone-on-start=true 